@echo off
cd /d "%~dp0In_bot"
echo Activating virtual environment...
call "%~dp0In_bot\.venv\Scripts\activate.bat"
echo Installing/checking dependencies...
pip install -r requirements.txt --quiet
echo Starting LanguageNut bot...
python main.py
pause
